# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20170803_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('template', 'template')], default='text', max_length=20),
        ),
    ]
