# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20170807_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCohortPatient',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.CharField(max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curation_status', models.CharField(choices=[('PENDING', 'pending'), ('INPROGRESS', 'inprogress'), ('COMPLETED', 'completed')], default='PENDING', max_length=20, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_project_patient', to='patients.Cohort')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_project_cohort', to='patients.Patient')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cohort_patient', to='patients.Project')),
            ],
            options={
                'db_table': 'curation_project_cohort_patient',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectcohortpatient',
            unique_together=set([('cohort', 'project', 'patient')]),
        ),
    ]
