# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20170808_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.CharField(max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=1000)),
                ('template', models.TextField()),
                ('place_holders', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curation_email_template',
            },
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number')], default='text', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set([('name', 'is_active')]),
        ),
    ]
