# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0009_auto_20170809_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcohortpatient',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_project_cohort_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectcohortpatient',
            unique_together=set([('cohort', 'project', 'patient', 'curator')]),
        ),
    ]
