# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 17:12
from __future__ import unicode_literals

from django.db import migrations
import src.patients.models.project_cohort_patient
import src.patients.models.project_crf_template


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20170809_1558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projectcohortpatient',
            managers=[
                ('objects', src.patients.models.project_cohort_patient.ProjectCohortPatientManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectcrftemplate',
            managers=[
                ('objects', src.patients.models.project_crf_template.ProjectCrfTemplateManager()),
            ],
        ),
    ]
