# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20170822_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='curation_status',
        ),
    ]
