# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20170821_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='start',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code_type',
            field=models.CharField(max_length=100),
        ),
    ]
