# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20170821_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='cohort_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_encounters', to='patients.Cohort'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounters', to='patients.Patient'),
        ),
    ]
