# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20170821_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='code_type',
            field=models.CharField(choices=[('ICD9_Diagnosis', 'ICD9 Diagnosis'), ('ICD10_Diagnosis', 'ICD10 Diagnosis'), ('MEDCIN_Diagnosis', 'MEDCIN Diagnosis'), ('SNOMED_Diagnosis', 'SNOMED Diagnosis')], max_length=100),
        ),
    ]
