# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_auto_20170823_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_scheduled', to='patients.Appointment'),
        ),
    ]
