# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_auto_20170823_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='patients.Cohort'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
