# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_auto_20170823_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdemographic',
            old_name='patient',
            new_name='curation_patient',
        ),
        migrations.AddField(
            model_name='patientdemographic',
            name='patient_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
