# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_auto_20170824_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdemographic',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
    ]
