version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    ports:
      - "5432:5432"
    env_file: .env_dev

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: .env_dev
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    links:
      - postgres
