version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    container_name: postgres_1
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_USER=curation
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=curation

  app:
    image: api_dev:latest
    build:
      context: ./curation-api/
      dockerfile: ./compose/django/Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
