version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=src
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_DB=src

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=src
      - POSTGRES_PASSWORD=mysecretpass
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

