version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  app:
    image: curation:latest
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: .env
    volumes:
      - /usr/src/app/
      - /usr/src/app/static
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    ports:
      - "8000:5000"

  redis:
    image: redis:latest
