version: '2'

volumes:
  travis_postgres_data: {}
  travis_postgres_backup: {}

services:
  postgres:
    container_name: postgres_travis_1
    image: postgres:9.6
    volumes:
      - travis_postgres_data:/var/lib/postgresql/data
      - travis_postgres_backup:/backups
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_USER=curation
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=curation

  app:
    image: api:latest
    build:
      context: .
      dockerfile: ./curation-api/compose/django/Dockerfile
    user: django
    env_file: .env
    volumes:
      - /usr/src/app/
      - /usr/src/app/static
    depends_on:
      - postgres
    links:
      - postgres
