version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    container_name: postgres_travis_1
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  app:
    image: api:latest
    build:
      context: ./curation-api/
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: .env
    volumes:
      - /usr/src/app/
      - /usr/src/app/static
    command: /gunicorn.sh
    ports:
      - "80:5000"
    depends_on:
      - postgres
    links:
      - postgres
