# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170703_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
