# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170809_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(max_length=256, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_by', models.CharField(max_length=256, null=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curation_user_password_history',
            },
        ),
    ]
