# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordhistory',
            unique_together=set([('user', 'password')]),
        ),
    ]
