# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170818_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
