# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 06:02
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

def load_stores_from_sql():
    import os
    sql_statements = open(os.path.join(str(settings.APPS_DIR),'users/sql/permissions.sql'), 'r').read()
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170822_1413'),
    ]

    operations = [
        migrations.RunSQL(load_stores_from_sql()),
    ]
