# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170828_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationuser',
            name='is_account_locked',
            field=models.BooleanField(default=False),
        ),
    ]
